import AppKit
import ApplicationServices

public enum InsertionStrategy: String, Sendable {
    case accessibility
    case paste
}

public enum InsertionEvidence: Equatable, Sendable {
    /// The field's value was re-read and had changed.
    case verified
    /// Events were posted; the target could not be re-read to confirm.
    case posted
}

public enum InsertionBlock: Equatable, Sendable {
    case secureField
    case accessibilityDenied
    case allStrategiesFailed
    case noFrontmostApp
    case targetLost
}

public enum InsertionOutcome: Equatable, Sendable {
    case inserted(via: InsertionStrategy, evidence: InsertionEvidence)
    case copiedToClipboard(InsertionBlock)
    /// Nothing was typed, copied, or kept anywhere.
    case blocked(InsertionBlock)
}

enum StrategyAttempt {
    case inserted(InsertionEvidence)
    case declined
}

public enum Inserter {
    /// DECISION_INSERTION_POLICY: which strategies to try, in which order, for a given target.
    static func strategies(for target: InsertionTarget) -> [InsertionStrategy] {
        switch target.focused {
        case .textElement: return [.accessibility, .paste]
        case .other, .unknown: return [.paste]
        }
    }

    @MainActor
    public static func insert(_ text: String, into target: InsertionTarget) async -> InsertionOutcome {
        guard AXIsProcessTrusted() else { return copyToClipboard(text, because: .accessibilityDenied) }
        if Arming.focusIsSecure() { return .blocked(.secureField) }
        guard NSWorkspace.shared.frontmostApplication?.processIdentifier == target.app.pid else {
            return copyToClipboard(text, because: .targetLost)
        }
        for strategy in strategies(for: target) {
            let attempt: StrategyAttempt
            switch strategy {
            case .accessibility: attempt = AccessibilityWrite.attempt(text, into: target)
            case .paste: attempt = await PasteWrite.attempt(text, into: target)
            }
            if case .inserted(let evidence) = attempt { return .inserted(via: strategy, evidence: evidence) }
        }
        return copyToClipboard(text, because: .allStrategiesFailed)
    }

    public static func copyToClipboard(_ text: String, because block: InsertionBlock) -> InsertionOutcome {
        Clipboard.write(text)
        return .copiedToClipboard(block)
    }

    /// Plain copy with the same transient markings, for non-session flows (history menu, salvage).
    public static func copyToClipboard(_ text: String) {
        Clipboard.write(text)
    }
}

enum Clipboard {
    static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")

    /// Marked transient/auto-generated so clipboard managers skip it.
    static func write(_ text: String) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        pasteboard.setString("", forType: transientType)
        pasteboard.setString("", forType: autoGeneratedType)
    }
}

/// Replaces the selection (or inserts at the caret) through the accessibility API, then checks the value actually changed —
/// some apps report success and do nothing.
enum AccessibilityWrite {
    static func attempt(_ text: String, into target: InsertionTarget) -> StrategyAttempt {
        guard case .textElement(let element) = target.focused,
              let before = element.string(kAXValueAttribute) else { return .declined }
        guard AXUIElementSetAttributeValue(element, kAXSelectedTextAttribute as CFString, text as CFTypeRef) == .success,
              let after = element.string(kAXValueAttribute),
              after != before else { return .declined }
        return .inserted(.verified)
    }
}

/// Clipboard + ⌘V; verifies by re-reading the field when it is readable, and restores the previous
/// clipboard only if nothing else wrote to it meanwhile.
enum PasteWrite {
    static let settleDelay: Duration = .milliseconds(250)

    @MainActor
    static func attempt(_ text: String, into target: InsertionTarget) async -> StrategyAttempt {
        let pasteboard = NSPasteboard.general
        let snapshot = PasteboardSnapshot(of: pasteboard)
        let before = target.currentText()
        Clipboard.write(text)
        let ourChangeCount = pasteboard.changeCount
        guard KeyPress.commandV() else {
            snapshot.restore(to: pasteboard)
            return .declined
        }
        try? await Task.sleep(for: settleDelay)
        let evidence: InsertionEvidence
        if let before, let after = target.currentText(), after != before {
            evidence = .verified
        } else {
            evidence = .posted
        }
        if pasteboard.changeCount == ourChangeCount { snapshot.restore(to: pasteboard) }
        return .inserted(evidence)
    }
}

/// Concealed items (password managers) are never captured, so they can never be re-materialized.
struct PasteboardSnapshot {
    private let items: [[NSPasteboard.PasteboardType: Data]]

    init(of pasteboard: NSPasteboard) {
        items = (pasteboard.pasteboardItems ?? []).compactMap { item in
            if item.types.contains(Clipboard.concealedType) { return nil }
            var data: [NSPasteboard.PasteboardType: Data] = [:]
            for type in item.types {
                if let bytes = item.data(forType: type) { data[type] = bytes }
            }
            return data
        }
    }

    func restore(to pasteboard: NSPasteboard) {
        pasteboard.clearContents()
        guard !items.isEmpty else { return }
        let restored = items.map { data in
            let item = NSPasteboardItem()
            for (type, bytes) in data { item.setData(bytes, forType: type) }
            return item
        }
        pasteboard.writeObjects(restored)
    }
}

enum KeyPress {
    private static let vKeyCode: CGKeyCode = 9

    static func commandV() -> Bool {
        guard let source = CGEventSource(stateID: .combinedSessionState),
              let down = CGEvent(keyboardEventSource: source, virtualKey: vKeyCode, keyDown: true),
              let up = CGEvent(keyboardEventSource: source, virtualKey: vKeyCode, keyDown: false) else { return false }
        down.flags = .maskCommand
        up.flags = .maskCommand
        down.post(tap: .cghidEventTap)
        up.post(tap: .cghidEventTap)
        return true
    }
}
